---
minimum_pre_commit_version: 3.2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: check-merge-conflict
        args:
          - --assume-in-merge
      - id: check-yaml
      - id: check-ast
      - id: check-builtin-literals
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        name: Rewrite code for Py3.7+
        args:
          - --py37-plus

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        name: Reorder imports for Py3.7+
        args:
          - --py37-plus

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
        name: Autoformat Python code

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Lint Python code with flake8
        args:
          - --max-line-length=88
          - --ignore=E203
